In [1]:
import numpy as np


In [2]:
twoD = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
newArray  = np.insert(twoD, 0, [[10,11,12]],axis = 0)

In [4]:
print(newArray)

[[10 11 12]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [5]:
newsArray = np.insert(twoD,0,[[13,14,15]],axis = 1)
print(newsArray)

[[13  1  2  3]
 [14  4  5  6]
 [15  7  8  9]]


In [6]:
appendedArray = np.append(twoD,[[14,15,17]],axis = 0)
print(appendedArray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [14 15 17]]


In [7]:
def sorting(array, rowIndex, colIndex):
    if rowIndex >= len(array) or colIndex >= len(array[0]):
        print('There was an error')
    else:
        print(array[rowIndex][colIndex])
sorting(twoD,2,2)

9


In [8]:
def transversal(array):
    for i in range(len(array)):
        for j in range(len(array[1])):
            print(array[i][j])
transversal(twoD)

1
2
3
4
5
6
7
8
9


In [11]:
def search(array, value):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] == value:
                return 'The value is located in '+str(i)+" "+str(j)
            
    return 'There was an error'
search(twoD, 8)

'The value is located in 2 1'

In [12]:
newTd = np.delete(twoD, 0 , axis = 0)
print(newTd)

[[4 5 6]
 [7 8 9]]
